name: csocsort_szamla
description: Csocsort

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

version: 4.7.1+5138 # 5 is the number of an appbundle, the digits after is the version number

environment:
  sdk: '>=3.0.0'

dependencies:
  firebase_core: ^3.9.0
  http: ^1.2.2
  shared_preferences: ^2.1.0
  intl: ^0.20.2
  fluttertoast: ^8.2.1
  provider: ^6.0.5
  easy_localization: ^3.0.1
  app_links: ^3.5.0
  share_plus: ^10.1.3
  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^17.2.4
  connectivity_widget: ^3.0.0
  path_provider: ^2.0.14
  get_it: ^7.2.0
  expandable: ^5.0.1
  url_launcher: ^6.1.10
  in_app_purchase: ^3.2.3
  fl_chart: ^0.68.0
  permission_handler: ^11.1.0
  google_mobile_ads: ^5.2.0
  dynamic_color: ^1.7.0
  mobile_scanner: ^6.0.2
  material_color_utilities: ^0.11.1
  image_picker: ^1.1.2
  firebase_vertexai: ^1.0.4
  google_sign_in: ^6.2.2
  sign_in_with_apple: ^6.1.4
  path: ^1.9.1
  customized_keyboard: ^1.0.7  
  flutter_hooks: ^0.21.2
  qr: ^3.0.2

  
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # # The following adds the Cupertino Icons font to your application.
  # # Use with the CupertinoIcons class for iOS style icons.
  # cupertino_icons: ^1.0.5
  # collection: ^1.15.0-nullsafety.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  msix: ^3.11.1
  flutter_lints: ^5.0.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/translations/
    - assets/images/dogLightTheme/
    - assets/images/dogDarkTheme/
    - assets/images/dodoBackgroundLightTheme/
    - assets/images/dodoBackgroundDarkTheme/

msix_config:
  display_name: Dodo - secure bill splitting	
  publisher_display_name: DevsWithTheDodos
  identity_name: 26756DevsWithTheDodos.Lender
  logo_path: ./assets/dodo.png
  publisher: CN=82952EEE-FBE0-4538-ACE4-293472CC6306
  store: true